name: Workflow for Codecov example-php
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up php 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, apcu, memcached, redis, pdo_sqlite
          coverage: xdebug
          tools: composer, cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Get date part for cache key
        id: key-date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json', 'TestApp/composer.json') }}

      - name: Install dependencies
        run: composer install -n && composer dump-autoload

      - name: Install dependencies
        working-directory: ./TestApp
        run: composer install -n && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Run PHPCS
        id: phpcs
        run: vendor/bin/phpcs -s -n --report-full --report-checkstyle=./phpcs-report.xml src/ tests/ TestApp/src TestApp/tests

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml

      - name: Run PSALM
        run: vendor/bin/psalm --output-format=github
